action_list:
  -
    action:
      点赞
    keyword_list:
      - ^赞\d*$
      - ^点赞$
  -
    action:
      评论
    keyword_list:
      - ^评论\d+$
      - ^评论$
      - ^我来说两句$
  -
    action:    
      转发
    keyword_list:
      - ^转发$
      - ^转发\d+$
      - ^快转$
  -
    action:
      点击纯数字
    keyword_list:
      - ^\d+$
  - action:
      播放视频
    keyword_list:
      - ^第\d+集$
      - \d+:\d
      - \d+.{1,3}观看
      - 播放
  - action:
      进入自媒体主页
    keyword_list:
      - ^.{1,20}[网|(观察)|(新闻)|(官方账号)|(官方微博)]$
      - 查看主页
  - action:
      关注用户
    keyword_list:
      - 关注
      - follow
  -
    action:
      发送私信
    keyword_list:
      - ^发送$
  -
    action:
      观看直播
    keyword_list:
      - ^直播$
      - ^直播中$
  - action:
      申请加群
    keyword_list:
      - ^申请加群$
      - ^加群$
