-
  app_name:
    新浪微博
  app_package:
    com.sina.weibo
  app_activity:
    .MainTabActivity
-
  app_name:
    央视新闻
  app_package:
    cn.cntvnews
  app_activity:
    com.torch.open.shell.EntryActivity
-
  app_name:
    喜马拉雅
  app_package:
    com.ximalaya.ting.android
  app_activity:
    .host.activity.MainActivity
-
  app_name:
    QQ音乐
  app_package:
    com.tencent.qqmusic
  app_activity:
    .activity.AppStarterActivity
-
  app_name:
    淘宝
  app_package:
    com.taobao.taobao
  app_activity:
    com.taobao.tao.welcome.Welcome
-
  app_name:
    QQ
  app_package:
    com.tencent.mobileqq
  app_activity:
    .activity.SplashActivity
-
  app_name:
    clash
  app_package:
    com.github.kr328.clash
  app_activity:
    .MainActivity
-
  app_name:
    百度手机助手
  app_package:
    com.baidu.appsearch
  app_activity:
    .SplashActivity
